### ISSUE TITLE
Estas variables no se están utilizando

### ISSUE THREAD

**Issue by josejuansanchez** [jacobo87/IAW-Practica07#2]
https://github.com/jacobo87/IAW-Practica07/blob/a518b07be6338821a9a01d740973683ec47d2f0d/balanceador_nginx.sh#L5

Podrías hacer que estos valores se reemplazaran de forma automática en el archivo de configuración *default* de nginx.

**Comment by jacobo87** [comment]
Sigo sin dar con la clave del archivo de configuración de los sitios por defecto ``/etc/nginx/sites-enabled/default``, cuando lanzo el script:
```
ubuntu@ip-172-31-16-6:~$ sudo ./balanceador_nginx.sh 
+ cp -r /home/ubuntu/IAW-Practica07/README.md /home/ubuntu/IAW-Practica07/balanceador_nginx.sh /home/ubuntu/IAW-Practica07/default /home/ubuntu/
+ apt-get update
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Fetched 210 kB in 0s (548 kB/s)
Reading package lists... Done
+ apt-get install nginx -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nginx is already the newest version (1.18.0-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 33 not upgraded.
+ cp default /etc/nginx/sites-enabled/
+ systemctl restart nginx.service
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
```
Ejecuto ``journalctl -xe``:

```
-- The process' exit code is 'exited' and its exit status is 1.
Nov 17 07:16:29 ip-172-31-16-6 systemd[1]: nginx.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit nginx.service has entered the 'failed' state with result 'exit-code'.
Nov 17 07:16:29 ip-172-31-16-6 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: A start job for unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
```
He probado varias formas del contenido de ```default``` incluido las más simples. Para que haga de proxy inverso, ¿debe de empezar como ```http {```?
Hay algunos que ví, lo etiquetan como ``server {``.

> El archivo default está actualizado desde 17/11/20 08:27.

**Comment by josejuansanchez** [comment]
Prueba con esta configuración básica en el archivo `default`.

```
upstream frontend {
   server  172.31.88.61;
   server  172.31.90.13;
}

server {
   listen 80;

   location / {
      proxy_pass http://frontend;
   }
}
```

**Comment by jacobo87** [comment]
Perfecto, aunque no entiendo, ¿no es necesario abrir con la etiqueta ``http {}``?. Todo ha funcionado a la perfección, me apunto los fallos y las dudas para el próximo día.

Gracias.

**Comment by josejuansanchez** [comment]
La directiva `http` aparece en el archivo de configuración `/etc/nginx/nginx.conf` y desde ese archivo se incluyen los archivos de configuración de los servidores virtuales que están en `/etc/nginx/sites-enabled/`. El apartado del archivo d configuración `/etc/nginx/nginx.conf` que hace referencia a la directiva `http` tiene los siguientes `includes`:

```
http {
   ...
   include /etc/nginx/conf.d/*.conf;
   include /etc/nginx/sites-enabled/*;
}
```

Por lo tanto, los archivos de configuración que tengamos para los servidores virtuales en `/etc/nginx/sites-enabled/`no necesitan incluir la directiva `http` porque sería redundante.

Aquí te dejo un ejemplo del archivo de configuración `default` que podríamos tener en el directorio `/etc/nginx/sites-enabled/`:

```
   upstream frontend {
      server  172.31.88.61;
      server  172.31.90.13;
   }

   server {
      listen 80;
      location / {
         proxy_pass http://frontend;
      }
   }
```

En la documentación de la web oficial muestran cuáles son las directivas que se pueden pueden poner en el primer nivel. Aquí te dejo la URL: [Creating NGINX Plus and NGINX Configuration Files](https://docs.nginx.com/nginx/admin-guide/basic-functionality/managing-configuration-files/#contexts).

Las directivas de primer nivel nos permiten aplicar configuraciones sobre los diferentes tipos de tráfico que puede existir en el servidor. Las opciones disponibles son:

- events – General connection processing
- http – HTTP traffic
- mail – Mail traffic
- stream – TCP and UDP traffic
